<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="DESKTOP-8S8SJ7F" failures="1" tests="1" name="Default test(failed)" time="14.095" errors="0" timestamp="2023-01-05T23:16:18 IST">
  <testcase classname="TestCases.LoginPageTest" name="LoginAppTest" time="2.642">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/inventory.h]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/inventory.h]
at TestCases.LoginPageTest.LoginAppTest(LoginPageTest.java:59)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- LoginAppTest -->
  <testcase classname="TestCases.LoginPageTest" name="VerifyLoginLogoTest" time="0.0">
    <ignored/>
  </testcase> <!-- VerifyLoginLogoTest -->
  <testcase classname="TestCases.LoginPageTest" name="VerifyBotLogoTest" time="0.0">
    <ignored/>
  </testcase> <!-- VerifyBotLogoTest -->
  <testcase classname="TestCases.LoginPageTest" name="verifyTitleTest" time="0.0">
    <ignored/>
  </testcase> <!-- verifyTitleTest -->
  <testcase classname="TestCases.LoginPageTest" name="VerifyLabelOfInventryTest" time="0.0">
    <ignored/>
  </testcase> <!-- VerifyLabelOfInventryTest -->
  <testcase classname="TestCases.LoginPageTest" name="verifyCurrentUrlTest" time="0.0">
    <ignored/>
  </testcase> <!-- verifyCurrentUrlTest -->
</testsuite> <!-- Default test(failed) -->
